### ISSUE TITLE
Reorder render layers (up/down)

### ISSUE THREAD

**Issue by Inaztm** [clabe45/vidar#56]
How to reorder render layers in runtime?

**Comment by clabe45** [comment]
You can modify the `Movie#layers` array like this:
```js
var last = movie.layers.pop();
movie.layers.push(last);
```

**Comment by Inaztm** [comment]
> You can modify the `Movie#layers` array like this:
> 
> ```js
> var last = movie.layers.pop();
> movie.layers.unshift(last);
> ```

Get e errors when write code:
```js
layers.forEach((layer) => {
    this.movie.layers.pop();
    this.movie.layers.unshift(layer);
});
```
```
angular.js:14642 DOMException: Failed to execute 'createMediaElementSource' on 'AudioContext': HTMLMediaElement already connected previously to a different MediaElementSourceNode.
    at Proxy.attach (https://cdn.jsdelivr.net/npm/vidar@0.7.0/dist/vidar-iife.min.js:7:8990)
    at Object.set (https://cdn.jsdelivr.net/npm/vidar@0.7.0/dist/vidar-iife.min.js:7:13766)
    at Proxy.unshift (<anonymous>)
    at http://newsroom.local/assets/admin.js?v={uniq_version}:172114:42
    at Array.forEach (<anonymous>)
    at http://newsroom.local/assets/admin.js?v={uniq_version}:172113:31
    at http://newsroom.local/assets/admin.js?v={uniq_version}:20659:32
    at completeOutstandingRequest (http://newsroom.local/assets/admin.js?v={uniq_version}:6632:11)
    at http://newsroom.local/assets/admin.js?v={uniq_version}:6912:8 "Possibly unhandled rejection: {"stack":"Error: Failed to execute 'createMediaElementSource' on 'AudioContext': HTMLMediaElement already connected previously to a different MediaElementSourceNode.\n    at Proxy.attach (https://cdn.jsdelivr.net/npm/vidar@0.7.0/dist/vidar-iife.min.js:7:8990)\n    at Object.set (https://cdn.jsdelivr.net/npm/vidar@0.7.0/dist/vidar-iife.min.js:7:13766)\n    at Proxy.unshift (<anonymous>)\n    at http://newsroom.local/assets/admin.js?v={uniq_version}:172114:42\n    at Array.forEach (<anonymous>)\n    at http://newsroom.local/assets/admin.js?v={uniq_version}:172113:31\n    at http://newsroom.local/assets/admin.js?v={uniq_version}:20659:32\n    at completeOutstandingRequest (http://newsroom.local/assets/admin.js?v={uniq_version}:6632:11)\n    at http://newsroom.local/assets/admin.js?v={uniq_version}:6912:8"}"
(anonymous) @ angular.js:14642
(anonymous) @ angular.js:11102
processChecks @ angular.js:17026
$digest @ angular.js:18182
$apply @ angular.js:18480
(anonymous) @ angular.js:20397
completeOutstandingRequest @ angular.js:6362
(anonymous) @ angular.js:6642
setTimeout (async)
Browser.self.defer @ angular.js:6640
timeout @ angular.js:20387
sortLayersByGroups @ video-composite.directive.js:535
(anonymous) @ video-composite.directive.js:106
r @ vidar-iife.js:76
addLayerToGroup @ VideoCompositeService.js:60
(anonymous) @ VideoCompositeService.js:49
addLayerGroup @ VideoCompositeService.js:48
setupMovie @ video-composite.directive.js:149
(anonymous) @ video-composite.directive.js:59
script.onload @ video-composite.js:26
load (async)
setupVidar @ video-composite.js:24
VideoCompositeController @ video-composite.directive.js:59
invoke @ angular.js:5040
$controllerInit @ angular.js:10960
nodeLinkFn @ angular.js:9840
compositeLinkFn @ angular.js:9149
compositeLinkFn @ angular.js:9152
publicLinkFn @ angular.js:9014
lazyCompilation @ angular.js:9405
boundTranscludeFn @ angular.js:9192
controllersBoundTransclude @ angular.js:9959
link @ ui-bootstrap-tpls.js:3953
(anonymous) @ angular.js:1385
invokeLinkFn @ angular.js:10520
nodeLinkFn @ angular.js:9909
compositeLinkFn @ angular.js:9149
nodeLinkFn @ angular.js:9903
compositeLinkFn @ angular.js:9149
nodeLinkFn @ angular.js:9903
(anonymous) @ angular.js:10248
processQueue @ angular.js:17000
(anonymous) @ angular.js:17044
$digest @ angular.js:18182
$apply @ angular.js:18480
(anonymous) @ angular.js:27290
defaultHandlerWrapper @ angular.js:3771
eventHandler @ angular.js:3759
vidar-iife.js:183 Uncaught (in promise) TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at vidar-iife.js:183
    at u (vidar-iife.js:250)
    at Proxy._renderLayers (vidar-iife.js:1876)
    at Proxy._render (vidar-iife.js:1825)
    at vidar-iife.js:1931
    at new Promise (<anonymous>)
    at Proxy.refresh (vidar-iife.js:1929)
    at vidar-iife.js:1635
    at r (vidar-iife.js:76)
```

**Comment by clabe45** [comment]
I just fixed this in 0b770529c8d35822c9d908ca46cbe0977bf685cd. I will release v0.8.0 with a guide for migrating soon.

**Comment by Inaztm** [comment]
I have same errors on 0.8.0, example https://codesandbox.io/s/frosty-silence-xcz6v?file=/src/index.js

**Comment by Inaztm** [comment]
> I just fixed this in [0b77052](https://github.com/clabe45/vidar/commit/0b770529c8d35822c9d908ca46cbe0977bf685cd). I will release v0.8.0 with a guide for migrating soon.

I have same errors on 0.8.0, example https://codesandbox.io/s/frosty-silence-xcz6v?file=/src/index.js

**Comment by clabe45** [comment]
Thanks for letting me know. Try this.

**Comment by Inaztm** [comment]
> Thanks for letting me know. Try this.

Thanks
